[dependencies]

[package]
  cjc-version = "0.53.4"
  compile-option = "-Oz"
  description = "ADIF Parser"
  link-option = ""
  name = "adif_parser_cj"
  output-type = "dynamic"
  src-dir = "src"
  target-dir = ""
  version = "0.0.2"
  package-configuration = {}
